site_name: CIT Student's guide to IoT
site_url: https://sitename.example
site_description: A comprehensive guide for CIT students on IoT topics.
site_author: Nurlan Aliyev

repo_url: https://github.com/nurlan-aliyev/cit-students-guide-to-iot
repo_name: nurlan-aliyev/cit-students-guide-to-iot

theme:
  name: material
  icon:
    logo: fontawesome/solid/microchip
  font:
    text: Poppins
    code: Roboto Mono
  # logo: assets/logo.png
  # favicon: assets/favicon.ico
  features:
    - navigation.footer
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    # - toc.integrate
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: deep purple

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

nav:
  - Home: 'index.md'
  - 1. Introduction to IoT and Arduino: 'introduction.md'
  - 2. Getting Started: 'getting-started.md'
  - 3. Programming Basics : 'programming-basics.md'
  - 4. Input/Output Operations: 'io-operations.md'
  - 5. Essential Functions: 'necessary-functions.md'
  - Useful Links: 'useful-links.md'


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nurlan-aliyev/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nurlan-aliyev-18b023220/

copyright: Copyright &copy; 2025 Nurlan Aliyev